# Generated by Django 3.2 on 2021-05-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviegenerator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField(max_length=500)),
                ('gender', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('M', 'Movie'), ('TV', 'TV Show')], max_length=2)),
                ('rating', models.IntegerField()),
                ('link', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='TextField',
        ),
    ]
