# Generated by Django 3.2 on 2021-05-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviegenerator', '0003_auto_20210511_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='production',
            name='overview',
        ),
        migrations.AddField(
            model_name='production',
            name='id_api',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='production',
            name='link',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='production',
            name='rating',
            field=models.IntegerField(default=None),
        ),
    ]
