# Generated by Django 3.2 on 2021-05-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviegenerator', '0004_auto_20210513_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='img',
            field=models.TextField(default='', max_length=600),
        ),
    ]
