# Generated by Django 3.2 on 2021-05-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviegenerator', '0005_production_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='type_of',
            field=models.CharField(choices=[('M', 'Movie'), ('TV', 'TV Show')], max_length=10),
        ),
    ]
